module.exports = {
  apps: [
    {
      name: "onui-asi",
      script: "/home/scottk/Projects/onui-ASI/scripts/run-uvicorn.sh",
      interpreter: "bash",
      cwd: "/home/scottk/Projects/onui-ASI",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "1G",
      env_file: "/home/scottk/Projects/onui-ASI/.env",
      error_file: "/home/scottk/Projects/onui-ASI/logs/pm2-error.log",
      out_file: "/home/scottk/Projects/onui-ASI/logs/pm2-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
    },
    {
      name: "onui-ngrok",
      script: "/home/scottk/Projects/onui-ASI/scripts/run-ngrok.sh",
      interpreter: "bash",
      cwd: "/home/scottk/Projects/onui-ASI",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      error_file: "/home/scottk/Projects/onui-ASI/logs/ngrok-error.log",
      out_file: "/home/scottk/Projects/onui-ASI/logs/ngrok-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
    },
  ],
};
